### ISSUE TITLE
TypeError: fn is not a function

### ISSUE THREAD

**Issue by bjxke** [briantanner/eris-lavalink#2]
Not quite sure how to solve this.
```
TypeError: fn is not a function
    at Map.processQueue (/Users/air/Documents/Adonis/node_modules/eris-lavalink/src/PlayerManager.js:125:9)
    at Map.queueFailover (/Users/air/Documents/Adonis/node_modules/eris-lavalink/src/PlayerManager.js:115:25)
    at Map.shardReady (/Users/air/Documents/Adonis/node_modules/eris-lavalink/src/PlayerManager.js:160:18)
    at emitOne (events.js:120:20)
    at Object.emit (events.js:210:7)
    at Function.shard.on (/Users/air/Documents/Adonis/node_modules/eris/lib/gateway/ShardManager.js:56:29)
    at new Func (/Users/air/Documents/Adonis/node_modules/rethinkdbdash/lib/term.js:3053:19)
    at Function.Term.expr (/Users/air/Documents/Adonis/node_modules/rethinkdbdash/lib/term.js:2339:12)
    at /Users/air/Documents/Adonis/node_modules/rethinkdbdash/lib/term.js:2364:40
    at Object.loopKeys (/Users/air/Documents/Adonis/node_modules/rethinkdbdash/lib/helper.js:56:14)
    at Function.Term.expr (/Users/air/Documents/Adonis/node_modules/rethinkdbdash/lib/term.js:2362:12)
    at /Users/air/Documents/Adonis/node_modules/rethinkdbdash/lib/term.js:2364:40
    at Object.loopKeys (/Users/air/Documents/Adonis/node_modules/rethinkdbdash/lib/helper.js:56:14)
    at Function.Term.expr (/Users/air/Documents/Adonis/node_modules/rethinkdbdash/lib/term.js:2362:12)
    at /Users/air/Documents/Adonis/node_modules/rethinkdbdash/lib/term.js:2364:40
    at Object.loopKeys (/Users/air/Documents/Adonis/node_modules/rethinkdbdash/lib/helper.js:56:14)
```

**Comment by minemidnight** [comment]
This was fixed [here](https://github.com/briantanner/eris-lavalink/commit/9a374171525fa8466a2b74c3b7b6ed0ecf2e565a)
