### ISSUE TITLE
Error: unexpected server response (404)

### ISSUE THREAD

**Issue by ETLegacyy** [briantanner/eris-lavalink#22]
I ran my bot, and then it gave me this error:
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (404)
    at ClientRequest._req.on (/root/TrinityAlpha/node_modules/ws/lib/WebSocket.j                                                                                                 s:653:21)
    at ClientRequest.emit (events.js:182:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:538:21                                                                                                 )
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at Socket.socketOnData (_http_client.js:425:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:277:12)
    at readableAddChunk (_stream_readable.js:262:11)
    at Socket.Readable.push (_stream_readable.js:217:10)
    at TCP.onread (net.js:638:20)
Emitted 'error' event at:
    at Map.onError (/root/TrinityAlpha/node_modules/eris-lavalink/src/PlayerMana                                                                                                 ger.js:142:21)
    at Lavalink.emit (events.js:182:13)
    at WebSocket.ws.on (/root/TrinityAlpha/node_modules/eris-lavalink/src/Lavali                                                                                                 nk.js:77:9)
    at WebSocket.emit (events.js:182:13)
    at WebSocket.finalize (/root/TrinityAlpha/node_modules/ws/lib/WebSocket.js:1                                                                                                 82:41)
    at ClientRequest._req.on (/root/TrinityAlpha/node_modules/ws/lib/WebSocket.j                                                                                                 s:653:12)
    at ClientRequest.emit (events.js:182:13)
    [... lines matching original stack trace ...]
    at TCP.onread (net.js:638:20)

**Comment by AnotherGenZ** [comment]
This may be due to you passing a host that points at the LavaLink REST port. Please make sure that the host you're giving to eris-lavalink is indeed the LavaLink WS port.
